# Generated by Django 4.2.26 on 2025-11-28 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
